/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppDataContext`; params?: Router.UnknownInputParams; } | { pathname: `/bank-accounts`; params?: Router.UnknownInputParams; } | { pathname: `/enter-passcode`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/company-verification` | `/company-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/create-passcode` | `/create-passcode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/support` | `/support`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AppDataContext`; params?: Router.UnknownOutputParams; } | { pathname: `/bank-accounts`; params?: Router.UnknownOutputParams; } | { pathname: `/enter-passcode`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboard)'}/company-verification` | `/company-verification`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboard)'}/create-passcode` | `/create-passcode`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboard)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboard)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/support` | `/support`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AppDataContext${`?${string}` | `#${string}` | ''}` | `/bank-accounts${`?${string}` | `#${string}` | ''}` | `/enter-passcode${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboard)'}/company-verification${`?${string}` | `#${string}` | ''}` | `/company-verification${`?${string}` | `#${string}` | ''}` | `${'/(onboard)'}/create-passcode${`?${string}` | `#${string}` | ''}` | `/create-passcode${`?${string}` | `#${string}` | ''}` | `${'/(onboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboard)'}/profile-setup${`?${string}` | `#${string}` | ''}` | `/profile-setup${`?${string}` | `#${string}` | ''}` | `${'/(onboard)'}/verify-phone${`?${string}` | `#${string}` | ''}` | `/verify-phone${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/support${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppDataContext`; params?: Router.UnknownInputParams; } | { pathname: `/bank-accounts`; params?: Router.UnknownInputParams; } | { pathname: `/enter-passcode`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/company-verification` | `/company-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/create-passcode` | `/create-passcode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboard)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/support` | `/support`; params?: Router.UnknownInputParams; };
    }
  }
}
